apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blue-green-deployment

namePrefix: green-


resources:
- ../../base

labels:
- includeSelectors: true
  pairs:
    environment: production
    version: green
patches:
- path: deployment-patch.yaml
- path: service-patch.yaml
