apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blue-green-deployment

namePrefix: green-

commonLabels:
  version: green
  environment: production

resources:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml
  - service-patch.yaml

# images:
#   - name: yourusername/nginx-blue
#     newName: yourusername/nginx-green
#     newTag: latest
