apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

namePrefix: blue-

commonLabels:
  version: blue
  environment: production

resources:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml

