apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: webapp-preview-route
  namespace: dev-blue-green-deployment
spec:
  parentRefs:
    - name: eg
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /preview
      backendRefs:
        - name: hello-world-app-preview-svc   # preview service
          port: 80
