apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-dev
spec:
  destination:
    namespace: dev-blue-green-deployment        
    name: in-cluster
  source:
    repoURL: https://github.com/abhilashshettigar/blue-green-deployment.git
    targetRevision: main
    path: k8s/overlays/dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
