apiVersion: v1
kind: Service
metadata:
  name: hello-world-app-preview-svc
  labels:
    app: hello-world-app-preview-svc
spec:
  type: LoadBalancer
  selector:
    app: hello-world-app
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
